spring:
  application:
    name: discovery-eureka-service

  profiles:
    default: dev

  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      retry:
        initial-interval: 3000
        max-interval: 10000
        max-attempts: 10

  config:
    import: "configserver:"

server:
  port: 8761